<?php /** @var $this Gaiproject_Restock_Block_Catalog_Product_View_Options_Type_Cron */ ?>
<?php $_option = $this->getOption(); ?>
<dt><label<?php if ($_option->getIsRequire()) echo ' class="required"' ?>><?php if ($_option->getIsRequire()) echo '<em>*</em>' ?><?php echo  $this->htmlEscape($_option->getTitle()) ?></label>
    <?php echo $this->getFormatedPrice() ?></dt>
<dd<?php if ($_option->decoratedIsLast){?> class="last"<?php }?>>
    <div class="input-box">
        <input type="text"
               id="options_<?php echo $_option->getId() ?>_cron"
               class="<?php echo $_option->getIsRequire() ? ' required-entry' : '' ?> cron"
               name="options[<?php echo $_option->getId() ?>]"
               value="<?php echo $this->escapeHtml($this->getDefaultValue()) ?>" />
    </div>
    <script>
	    jQuery(function(){
	    	jQuery('.cron').jqCron();
		});
	</script>
</dd>